application: 
  port: 8000
  host: 0.0.0.0
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "example"
  database_name: "bookr"
  require_ssl: false
email_client: 
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "my-secret-token"
  timeout_millis: 10000
redis_uri: "redis://127.0.0.1:6379"
jwt_settings:
  secret: "my_secret"
  expires_in: "60m"
  max_age: 60
gmaps_client:
  api_url: "https://maps.googleapis.com/maps/api/geocode/json"
  api_key: "my-secret-token"