[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = {version = "4.3", default-features = false, features = ["macros"]}
async-graphql = { version = "5.0", features = ["chrono", "dataloader"] }
async-graphql-actix-web = "5.0" 
chrono = "0.4.23"
dotenv = "0.15.0"
futures = "0.3.21"
sea-orm = { version = "^0.9.0", features = [ 
    "sqlx-postgres", 
    "runtime-async-std-native-tls", 
    "macros",
    "with-chrono"
] }
sea-orm-migration = "^0.9.0"